/*
 *OBJECT ORIENTED PROGRAMMING (CS F213)
 *
 *Code written by:
 *MONIS MUSHTAQUE
 *
 *monis.mushtaque@gmail.com
 *
 *Date: 19th July 2020
*/

package Multiplayer_Game;

import java.util.*;

class PlayerFactory {
	
	int num_of_players;									     //Number of players to be generated by the factory
	Moderator mainM;									     //The moderator under which every player will play the game
	
	PlayerFactory(int n, Moderator m)						 //Constructor for the PlayerFactory class.
	{
		num_of_players=n;
		mainM=m;
	}
	
	RandomNumberGenerator RNG=new RandomNumberGenerator(); 
	
	ArrayList<Player> getPlayerList()                         //This method returns an ArrayList of n players objects.
	{
		ArrayList<Player> AL_players=new ArrayList<Player>();
		try
		{
			for(int i=0; i<num_of_players; i++){
			String playerName= "Player "+ String.valueOf(i+1);
			Player p=new Player(playerName, mainM);
			p.setPlayerCards(RNG.getAL());					  //Using the getAL() method from RandomNumberGenerated class, we get an arraylist of 10 integers
			AL_players.add(p);								  //and assign that list to each player using setPlayerCards() method present in the Player class
			}
		}
		catch(ArrayIndexOutOfBoundsException e){
			System.out.println("Array index is out of bound.");
		}
		return AL_players;
	}
}
